name: Android CI - Debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle CLI
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      - name: Build Debug APK
        # use system 'gradle' (not ./gradlew) — avoids missing wrapper issue
        run: gradle assembleDebug --no-daemon

      - name: Show APK output files (for debugging)
        run: |
          echo "Listing APK output folders..."
          ls -la app/build/outputs/apk || true
          ls -la app/build/outputs/apk/debug || true

      - name: Upload Debug APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # upload any debug apk(s) that were produced
          path: app/build/outputs/apk/debug/*.apk
